create table comment
(
    id       int8 generated by default as identity,
    message  varchar(256) not null,
    rating   int4         not null check (rating >= 0 AND rating <= 10),
    place_id int8,
    user_id  int8,
    primary key (id)
);
create table place
(
    id            int8 generated by default as identity,
    count         int8   default 0,
    description   varchar(255) not null,
    full_name     varchar(255) not null,
    rating        float8 default 0.0 check (rating >= 0 AND rating <= 10),
    short_name    varchar(255) not null,
    type_place_id int8,
    primary key (id)
);
create table role
(
    id   int8 generated by default as identity,
    role varchar(255) not null,
    primary key (id)
);
create table type_place
(
    id   int8 generated by default as identity,
    type varchar(255) not null,
    primary key (id)
)
create table user_role
(
    user_id int8 not null,
    role_id int8 not null,
    primary key (role_id, user_id)
)
create table users
(
    id       int8 generated by default as identity,
    login    varchar(255) not null,
    password varchar(255) not null,
    primary key (id)
)
alter table if exists place
    add constraint UK_qjqkxhcm5kdy4lgf0qwjicq87 unique (description)
alter table if exists place
    add constraint UK_t0fa4pcwkfdwd4e91ougoriec unique (full_name)
alter table if exists place
    add constraint UK_m8waq1hbv8rib8q60s5j4cli1 unique (short_name)
alter table if exists role
    add constraint UK_bjxn5ii7v7ygwx39et0wawu0q unique (role)
alter table if exists type_place
    add constraint UK_3t5wybxae9dcb8iy75463lmqb unique (type)
alter table if exists users
    add constraint UK_ow0gan20590jrb00upg3va2fn unique (login)
alter table if exists users
    add constraint UK_r53o2ojjw4fikudfnsuuga336 unique (password)
alter table if exists comment
    add constraint FKch8bkgqt3v8yjo230lysj668h foreign key (place_id) references place
alter table if exists comment
    add constraint FKqm52p1v3o13hy268he0wcngr5 foreign key (user_id) references users
alter table if exists place
    add constraint FKs9jxnngmo9yrdkepl784c9v30 foreign key (type_place_id) references type_place
alter table if exists user_role
    add constraint FKa68196081fvovjhkek5m97n3y foreign key (role_id) references role
alter table if exists user_role
    add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users
